### ISSUE TITLE
document messages to/from Pd in the help files of send/receive

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pddp#20] opened 2021-11-21 21:39 UTC
and as a side topic of #19  , there is also the special names, that would be interesting to document somewhere

like [;pd dsp 1(, but you can also do [;pd quit( (which is important for the context of using pd with -batch, for example) or the [r pd-dsp-started], already in [samplerate~] helpfile , i know you can find some of them googling, but why not document some of them together somewhere in the manuals? (or maybe in the send receive helpfile)

**Comment by porres** [comment] 2021-11-22 04:30
I'll keep this issue as a request to improve the help file, as for adding sections to the manual as well, I agree and I have already mentioned this here https://github.com/pure-data/pddp/issues/14

**Comment by abreubacelar** [comment] 2021-11-22 08:46
a suggestion is that we can also use the opportunity and explain about the relationship between pd core and pd gui, and that you can also see all the messages being exchanged with -d n flag, also show that internally each patch has a special name, (I mean, that crazy name, that points to the canvas) but you can also use the name of the subpatch as pd-thename, and abstractions as pd-abstraction.pd and etc...

when I said about special names, pd and pd-dsp-started were examples, but we could also show that there are more, and pd core to pd gui

**Comment by abreubacelar** [comment] 2021-11-22 08:52
sorry, I commented on my phone and closed the issue accidentally...

**Comment by danomatika** [comment] 2021-11-22 09:08
There are also internal things such as #midi…

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by porres** [comment] 2021-11-24 02:18
I already documented some messages to Pd in https://github.com/pure-data/pure-data/pull/1455/commits/640cce0fa3d0f5b2e62769ffa3b6a20ed77e7156

There are still more messages to document, like messages to a canvas (for dynamic patching). I don't know of any other messages that are relevant to document from pd other than 'dsp-started' and that's already documented in [samplerate~], so I'm not sure what to add. 

I don't know about #midi messages, maybe dan can help. I'm closing this issue as it's also a duplicate of https://github.com/pure-data/pure-data/issues/1125 which my commit fully closes. We can reopen issues for more specific issues. But I also have brought this up to https://github.com/pure-data/pddp/issues/14 saying we could include these in the manual as well.

**Closed by porres** 2021-11-24 02:18 UTC
Labels: help-files
